# 개요

1. numpy 
2. pandas
3. torch로 vector, matrix 등 만들어보기

## 참고자료
* Official tutorial: https://docs.scipy.org/doc/numpy/reference/
* Stanford Univ. CS231 tutorial: http://cs231n.github.io/python-numpy-tutorial/

## 1. numpy, array, matrix 등

In [3]:
import warnings
warnings.filterwarnings("ignore")
#버전차이에서 나오는 워닝들을 무시하겠다.

In [1]:
import numpy as np

### 리스트, 행렬 선언

In [9]:
# list_name(변수명 설정) = ["item-1", "item-2", ... , "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [10]:
# append()로 리스트에 item 추가하기
c.append('new_item')
c.append(['new_item_list'])

print(c)

[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], 'new_item', ['new_item_list']]


In [7]:
a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])
c = np.array([["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [ ]:
# 배열(또는 행렬)을 1로 채우기
print(np.ones((1, 5))) #5개의 컬럼을 가진 1행을 1로 채우겠다.
print(np.ones((3, 2))) #2개의 컬럼을 가진 3행을 1로 채우겠다.

In [ ]:
# 배열(또는 행렬)을 0으로 채우기
print(np.zeros((1, 5))) #2개의 컬럼을 가진 3행을 0으로 채우겠다.
print(np.zeros((3, 2))) #2개의 컬럼을 가진 3행을 0으로 채우겠다.

In [11]:
# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step, ] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

#arange의 기능. 
#값을 하나만 입력할 경우 0부터 입력값 직전까지 순차적으로 하나씩 증가하는 리스트를 만들고.
#2개 입력 = 시작값과 종료값. 이때 종료값의 직전까지 리스트로 나타냄
#3개 입력 = 시작값, 종료값, 인터벌

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [12]:
# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))
# 최소값은 1로, 최대값은 10, 3행 2열의 리스트를 랜덤으로
mat3 = np.random.rand(3,2)
# 3x2 사이즈의 리스트를 랜덤하게 만든다. rand는 실수,

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[6 6]
 [6 4]
 [1 7]]
[[0.21353137 0.5803286 ]
 [0.37338214 0.83025624]
 [0.29842041 0.67949273]]


### 리스트 인덱싱(Indexing) & 슬라이싱(Slicing)

In [ ]:
# Indexing
a = [1,3,5,7,9,11]
print(a[2], a[5], a[-1])
#-1번지는 마지막

In [ ]:
# Slicing
b = [2,4,6,8,10]
print(b[2:]) #2번부터 끝까지
print(b[:2]) #2번까지
print(b[:]) #전체 배열

### numpy의 reshape (PyTorch의 view와 비교)

In [13]:
# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.64972745 0.11874656 0.31260641]
 [0.29470743 0.2029421  0.35462444]
 [0.724832   0.29429586 0.19196573]
 [0.3084738  0.03296973 0.02716816]
 [0.68759845 0.01595356 0.23215847]
 [0.77284347 0.07457119 0.29388426]]


In [14]:
# -1: all
print(mat1.reshape(1, -1).shape)
print(mat1.reshape(1, -1))
print("=====")
print(mat1.reshape(-1, 1).shape)
print(mat1.reshape(-1, 1))

#reshape(1,-1) 1개의 행으로 끝까지 재정렬
#reshape(-1,1) 1개의 열로 끝까지 재정렬
#-1은 x값이라고 생각하면 될듯.
#주어진 정보(행/열)이 불확실할때 사용

(1, 18)
[[0.64972745 0.11874656 0.31260641 0.29470743 0.2029421  0.35462444
  0.724832   0.29429586 0.19196573 0.3084738  0.03296973 0.02716816
  0.68759845 0.01595356 0.23215847 0.77284347 0.07457119 0.29388426]]
=====
(18, 1)
[[0.64972745]
 [0.11874656]
 [0.31260641]
 [0.29470743]
 [0.2029421 ]
 [0.35462444]
 [0.724832  ]
 [0.29429586]
 [0.19196573]
 [0.3084738 ]
 [0.03296973]
 [0.02716816]
 [0.68759845]
 [0.01595356]
 [0.23215847]
 [0.77284347]
 [0.07457119]
 [0.29388426]]


In [ ]:
print(mat1.reshape(2, 9).shape)
print(mat1.reshape(9, 2))

In [15]:
mat1.reshape(2,5)
#가지고 있는 숫자는 18개이기 때문에 2,5로 리셰이프를 하면 사이즈가 맞지 않기 때문에 오류가 난다.

ValueError: ignored

In [ ]:
# tensor 형태로 나타내기
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))
#벡터 : 행 또는 열이 하나인 것
#매트릭스 : 행과 열이 하나 이상인 것
#텐서 : 3차원 이상의 행열을 표현할때 사용

### matrix 또는 tensor 형태에서도 slicing이 가능합니다!

In [16]:
mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
mat2[:1,:3]
#행의 1번째까지, 열의 3번째까지 가져오는것이기 때문에 첫번째 행인 0, 1, 2, 3 중 3번쨰 열인 0, 1, 2 만 불러옴

array([[0, 1, 2]])

In [18]:
mat2[3, 0:2]
#3번 행인 12 13 14 15 부터 0부터 2까지 가져오기, 12 13만 가져옴

array([12, 13])

### Math Arithmetic Operations(사칙연산)

In [19]:
x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [20]:
# add
x + y
#같은 사이즈의 행열끼리 덧셈

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [23]:
x - y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [21]:
x * y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [22]:
x / y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [24]:
print(x ** 2)
print(np.power(x, 2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]
[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [25]:
np.dot(x, y)
#내적 구하기

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [ ]:
np.sqrt(x)
#제곱근 구하기

In [26]:
# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x * z1

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])

In [ ]:
print(z2.shape)
print(x.shape)
print(x * z2)

In [27]:
# 합
print(x)
print(x.sum(axis = 0))#열끼리
print(x.sum(axis = 1))#행끼리

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[21 27 33]
[ 9 27 45]


In [ ]:
# 평균
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))

In [ ]:
# 표준편차
print(x)
print(x.std(axis = 0))
print(x.std(axis = 1))

In [ ]:
print(x.T)
print(np.dot(x, z1.T))

### Other operations

In [ ]:
xx = np.random.rand(15)
print(xx)

In [ ]:
print(xx)
print(xx.argsort()) # axis를 활용해서 행렬(matrix)에도 적용할 수 있다.
#argsort : index번호를 알려줌
xx.sort()
print(xx)

## 2. Pandas

* https://pandas.pydata.org/pandas-docs/stable/

In [31]:
import pandas as pd

### Pandas Series 만들기

* pandas series는 1차원 데이터 집합

In [32]:
pd_series = pd.Series(index = ['a','b','c','d','e'], data=[1,2,3,4,5])
#index값, data:밸류
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [33]:
# Pandas Series의 기초 정보
print('차원:', pd_series.ndim)
print('형태: ', pd_series.shape)
print('총 원소의 수:', pd_series.size)

print('값:', pd_series.values)
print('인덱스:', pd_series.index)

차원: 1
형태:  (5,)
총 원소의 수: 5
값: [1 2 3 4 5]
인덱스: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### index를 활용한 데이터 탐색

In [39]:
# loc(index를 활용하여 access), iloc(integer location)

print(pd_series.loc['a'])
print(pd_series.iloc[0])

print(pd_series.loc[['a','c']])
print(pd_series.iloc[[0,2]])

1
1
a    1
c    3
dtype: int64
a    1
c    3
dtype: int64


### 데이터 삭제

In [ ]:
pd_series.drop('b')

In [ ]:
print(pd_series)
pd_series.drop('b', inplace=True)#인플레이스 true를 해줘야 완전히 삭제됨
print(pd_series)

### Pandas Dataframe 만들기

* 2차원 데이터 집합. 행렬과 비슷하게 row와 column을 갖고 있다

In [ ]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low=0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [ ]:
data_df.head()

In [ ]:
data_df.tail()

In [ ]:
data_df.shape

### Indexing and Slicing

In [ ]:
data_df[1:3]

In [ ]:
data_df.loc[1]

In [ ]:
data_df.loc[1]['C']

### Add, Remove and etc

In [ ]:
data_df['D'] = data_df['A'] >= 5
data_df

In [ ]:
data_df.drop('D', axis=1, inplace=True)

In [ ]:
data_df.sort_index(axis=0, ascending=False)